version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vitrygtr
      MYSQL_DATABASE: project
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: vitrygtr
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - my-network

  flask:
    build:
      context: ./Sprint3
    container_name: flask_container
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: vitrygtr
      DB_NAME: project
      LDAP_HOST: openldap
      LDAP_PORT: 389
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./Sprint3:/app
    networks:
      - my-network  # Added to the same network as mysql and openldap

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=rtlocal
      - LDAP_DOMAIN=rtlocal.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=rtlocal,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=rtlocal.com.ca.crt
    networks:
      - my-network  # Same network as mysql and flask

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - '8081:80'
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - my-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    ports:
      - "8082:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
    - ./certificates:/etc/certs  # Mount LDAP certificates
    command: ["start-dev"]
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:  # Defined "my-network" for common network
    driver: bridge  # Default bridge driver used
  wireguard-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.13.13.0/24

volumes:
  openldap_data:  # Defining volumes
  mysql_data:

